Feature/v14.0.0
epayco/resources pull request #68
Opened 2022-08-09 21:25 UTC by RicardoSaldarriagaPayco

2022-08-10 00:33 UTC, seboraid commented
@RicardoSaldarriagaPayco los reviews se los debes solicitar a tu lider técnico por favor.

2022-08-10 00:43 UTC, RicardoSaldarriagaPayco commented
@seboraid mi lider es Gilberto y no lo encuentro como revieew en este repo, podrias agregarlo tan amable

2022-08-10 16:19 UTC, asuajegilberto requested changes

2022-08-10 16:19 UTC, asuajegilberto commented on epayco-ng/src/app/services/epayco.service.ts
> +  configUrl = 'https://secure.epayco.io/validation/v1/reference/';
si esto sera por ambiente, deberia ir una variable de entorno

2022-08-10 16:19 UTC, asuajegilberto commented on epayco-ng/src/index.html
> +  <script type="text/javascript" src="https://epayco-checkout-testing.s3.amazonaws.com/checkout.preprod.js"></script>
si esto sera por ambiente, deberia ir una variable de entorno

2022-08-10 16:19 UTC, asuajegilberto commented on epayco-ng/src/app/components/response/response.component.ts
> +	transactionResponse:any;
falta tipado de datos

2022-08-10 16:19 UTC, asuajegilberto commented on epayco-ng/src/app/components/response/response.component.ts
> +    .subscribe((data: any) =>{
falta tipado de datos

2022-08-10 16:19 UTC, asuajegilberto commented on epayco-ng/src/main.ts
> +  .catch(err => console.error(err));
eliminar console.log

2022-08-10 17:16 UTC, RicardoSaldarriagaPayco commented on epayco-ng/src/main.ts
> +  .catch(err => console.error(err));
@asuajegilberto  se realizo eliminación correspondiente de console.log

2022-08-10 17:16 UTC, RicardoSaldarriagaPayco commented on epayco-ng/src/app/components/response/response.component.ts
> +    .subscribe((data: any) =>{
@asuajegilberto se realiza tipado correspondiente

2022-08-10 17:17 UTC, RicardoSaldarriagaPayco commented on epayco-ng/src/app/components/response/response.component.ts
> +	transactionResponse:any;
@asuajegilberto se realiza tipado correspondiente

2022-08-10 17:17 UTC, RicardoSaldarriagaPayco commented on epayco-ng/src/app/services/epayco.service.ts
> +  configUrl = 'https://secure.epayco.io/validation/v1/reference/';
@asuajegilberto se realiza ajuste correspondiente

2022-08-10 18:42 UTC, RicardoSaldarriagaPayco commented on epayco-ng/src/index.html
> +  <script type="text/javascript" src="https://epayco-checkout-testing.s3.amazonaws.com/checkout.preprod.js"></script>
se realiza ajustes correspondiente

2022-08-17 13:40 UTC, alexDevEpayco approved these changes

2022-08-17 13:40 UTC, merged